version: "3"

services:
  evento_frontend:
    build:
      context: evento_frontend
      dockerfile: prod.Dockerfile
    container_name: evento_frontend
    ports:
      - "10000:80"
    volumes:
      - ./evento:/app
      - /app/node_modules
    depends_on:
      - letsencrypt

  evento_insert:
    build:
      context: evento_insert
      dockerfile: prod.Dockerfile
    container_name: evento_insert
    ports:
      - "10001:80"
    volumes:
      - ./insertApp:/app
      - /app/node_modules
    depends_on:
      - letsencrypt

  backend:
    build:
      context: backend
      dockerfile: prod.Dockerfile
    container_name: evento_backend
    ports:
      - "10002:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - letsencrypt

  mongodb:
    image: mongo
    container_name: mongodb
    depends_on:
      - letsencrypt

  letsencrypt:
    image: linuxserver/swag
    container_name: swag
    volumes:
      - ./letsencryptPi/config:/config/
    ports:
      - "443:443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=evento.duckdns.org
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
    depends_on:
      - duckdns

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - SUBDOMAINS=eventos.duckdns.org
      - TOKEN=${DUCKDNSTOKEN}
