version: "3"

services:
  threeventsfiveone:
    image: 3vents51/3vents51_threeventsfiveone:latest
    container_name: evento_app
    ports:
      - "10000:80"
    volumes:
      - ./threeventsfiveone:/app
      - /app/node_modules
    depends_on:
      - letsencrypt

  insert-app:
    image: 3vents51/3vents51_insert-app:latest
    container_name: insert_app
    ports:
      - "10001:80"
    volumes:
      - ./insertApp:/app
      - /app/node_modules
    depends_on:
      - letsencrypt

  backend:
    image: 3vents51/3vents51_backend:latest
    container_name: backend
    ports:
      - "10002:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - letsencrypt

  mongodb:
    image: mongo
    container_name: mongodb
    depends_on:
      - letsencrypt

  letsencrypt:
    image: linuxserver/swag
    container_name: swag
    volumes:
      - .letsencryptStrato/config/:/config/
    ports:
      - "443:443"
      - "80:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=evento-leipzig.de
      - SUBDOMAINS=www, insert, backend
      - VALIDATION=http
      - EMAIL=business@evento-leipzig.de
