apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "mongodb-pvc"
  namespace: "evento-dev"
  labels:
    app: "mongodb"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
