apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "mongodb"
  namespace: "evento-dev"
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: "mongodb"
  template:
    metadata:
      labels:
        app: "mongodb"
    spec:
      containers:
        - name: "mongodb"
          image: "mongo"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 27017
              name: "mongodb"

          volumeMounts:
            - name: "mongodb-persistent-storage"
              mountPath: "/data/db"

      volumes:
        - name: "mongodb-persistent-storage"
          persistentVolumeClaim:
            claimName: "mongodb-pvc"
