name: Deploy

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_password }}
      - name: Build Backend Docker Containers
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: 3vents51_backend:latest
      - name: Build Frontend Docker Containers
        uses: docker/build-push-action@v2
        with:
          context: threeventsfiveone
          push: true
          tags: 3vents51_threeventsfiveone:latest
      - name: Build Insert-App Docker Containers
        uses: docker/build-push-action@v2
        with:
          context: insertApp
          push: true 
          tags: 3vents51_insert-app:latest

  deploy:
    runs-on: self-hosted
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_password }}
      - name: Pull Backend Docker Container
        run: docker pull 3vents51_backend:latest
      - name: Pull Frontend  Docker Containers
        run: docker pull 3vents51_threeventsfiveone:latest
      - name: Pull Insert-App Docker Container
        run: docker pull 3vents51_insert-app:latest
      - name: Create Environment File
        env:
          duckdns_token: ${{ secrets.PI }}
        run: touch .env.prod && echo "DUCKDNSTOKEN=$duckdns_token" >> .env.prod
      - name: Start Docker Containers
        run: docker-compose --env-file .env.prod -f docker-compose-prod.yml up -d --build
