name: CI

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build And Start Docker Container
        env:
          duckdns_token: ${{ PI }}
        run: docker-compose -e DUCKDNSTOKEN="$env:duckdns_token" -f docker-compose-prod.yml up -d --build
