name: Deploy

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Create Environment File
        env:
          duckdns_token: ${{ secrets.PI }}
        run: touch .env.prod && echo "DUCKDNSTOKEN=$duckdns_token" >> .env.prod
      - name: Build And Start Docker Container
        run: docker-compose --env-file .env.prod -f docker-compose-prod.yml up -d --build
