name: Deploy

on:
  push:
    branches: [ strato-server-test ]
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1


  build_frontend:
    needs: analyze
    name: Build And Push Events
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_password }}

      - name: Build Frontend Docker Containers
        uses: docker/build-push-action@v2
        with:
          platforms: linux/x86_64
          context: https://github.com/Maddi97/3vents51.git#develop:threeventsfiveone
          file: ./prod.Dockerfile
          push: true
          tags: ${{secrets.dockerhub_user}}/3vents51_threeventsfiveone:latest


  build_backend:
    needs: analyze
    name: Build And Push Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_password }}

      - name: Build Backend Docker Containers
        uses: docker/build-push-action@v2
        with:
          platforms: linux/x86_64
          context: https://github.com/Maddi97/3vents51.git#develop:backend
          file: ./prod.Dockerfile
          push: true
          tags: ${{secrets.dockerhub_user}}/3vents51_backend:latest


  build_insert-app:
    needs: analyze
    name: Build And Push Insert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_password }}

      - name: Build Insert-App Docker Containers
        uses: docker/build-push-action@v2
        with:
          platforms: linux/x86_64
          context: https://github.com/Maddi97/3vents51.git#develop:insertApp
          file: ./prod.Dockerfile
          push: true
          tags: ${{secrets.dockerhub_user}}/3vents51_insert-app:latest


  deploy:
    needs: [ build_backend, build_frontend, build_insert-app ]
    name: Deploy
    runs-on: strato
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_password }}

      - name: Pull Backend Docker Container
        run: docker pull ${{secrets.dockerhub_user}}/3vents51_backend:latest

      - name: Pull Frontend  Docker Containers
        run: docker pull ${{secrets.dockerhub_user}}/3vents51_threeventsfiveone:latest

      - name: Pull Insert-App Docker Container
        run: docker pull ${{secrets.dockerhub_user}}/3vents51_insert-app:latest

      - name: Create Environment File
        env:
          duckdns_token: ${{ secrets.PI }}
        run: touch .env.prod && echo "DUCKDNSTOKEN=$duckdns_token" >> .env.prod

      - name: Start Docker Containers
        run: docker-compose --env-file .env.prod -f docker-compose-prod-cd.yml up -d
